version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}

  api:
    image: 'node:10.16-alpine'
    restart: always
    links:
      - mongo
    working_dir: /home/node/app
    environment:
      - API_PORT=${API_PORT}
    volumes:
      - ./:/home/node/app
    ports:
      - ${API_PORT}:${API_PORT}
    command: "yarn api"
