version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}

  # api:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./api/Dockerfile
  #   image: ${DOCKER_NAME}_api
  #   container_name: ${DOCKER_NAME}_api_container
  #   expose:
  #     - "3001"
  #   command: yarn api

  # client:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   image: ${DOCKER_NAME}_client
  #   container_name: ${DOCKER_NAME}_client_container
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - api
  #   command: nginx -g "daemon off;"
